CREATE TABLE assets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    currency ENUM('JPY', 'USD') DEFAULT 'JPY',
    initial_balance DECIMAL(15, 2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



ALTER TABLE assets ADD COLUMN current_balance DECIMAL(10, 2);
